//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organize
    {
        public int Rank { get; set; }
        public long TourPlanId { get; set; }
        public long RegionId { get; set; }
        public string ToursitId { get; set; }
    
        public virtual TouristRegion TouristRegion { get; set; }
        public virtual TourPlan TourPlan { get; set; }
    }
}
