//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TourPlan()
        {
            this.Organizes = new HashSet<Organize>();
        }
    
        public long Id { get; set; }
        public Nullable<double> Balance { get; set; }
        public string TouristId { get; set; }
        public string GeoType { get; set; }
        public Nullable<int> FlightDuration { get; set; }
        public string Name { get; set; }
        public string LName { get; set; }
        public string PlanImage { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organize> Organizes { get; set; }
    }
}
